In [70]:
from sqlalchemy import create_engine, text

# DB 연결 설정
user = "postgres"
password = "0000"
host = "localhost"
port = "5432"
db_name = "rrt"

engine = create_engine(f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db_name}")

with engine.connect() as conn:
    result = conn.execute(text("SELECT current_database();"))  # ← 여기!
    print("Connected to:", result.scalar())

Connected to: rrt

In [44]:
from pathlib import Path
from datetime import datetime, timedelta
import pandas as pd
import re

dir_path = Path("../data/sample/Bloomberg/SPX_12232024/")
files = [f for f in dir_path.glob("*.xlsx") if not f.name.startswith("~$") and not f.name.startswith("ATMs")]
files.sort()

for f in files:
    print(f.name)

20241231.xlsx
20250117.xlsx
20250131.xlsx
20250221.xlsx
20250228.xlsx
20250321.xlsx
20250331.xlsx
20250417.xlsx
20250430.xlsx
20250516.xlsx
20250530.xlsx
20250620.xlsx
20250630.xlsx
20250718.xlsx
20250815.xlsx
20250919.xlsx
20250930.xlsx
20251017.xlsx
20251121.xlsx
20251219.xlsx
20251231.xlsx
20260116.xlsx
20260320.xlsx
20260618.xlsx
20261218.xlsx
20271217.xlsx
20281215.xlsx
20291221.xlsx

In [6]:
valid_call

,ticker,strike,bid,ask,last,ivm,volume,open,delta,gamma,theta,vega,rho,tau,type,tivm,tpxm
3,SPX 12/21/29 C400,400,0.1,0,5485,0,0,14,1,0,0,0,0,1823.662778,C,40.449263,5579.212973
4,SPX 12/21/29 C800,800,0,0,0,0,0,0,0,0,0,0,0,1823.662778,C,37.628031,5255.0825
5,SPX 12/21/29 C1200,1200,0,0,0,0,0,0,0,0,0,0,0,1823.662778,C,35.277992,4934.138518
6,SPX 12/21/29 C1600,1600,0,0,0,0,0,0,0,0,0,0,0,1823.662778,C,33.080748,4616.402073
7,SPX 12/21/29 C1800,1800,0,0,3102.399902,0,0,0,0,0,0,0,0,1823.662778,C,32.030175,4458.653046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,SPXW 12/31/24 C7400,7400,0,0.05,0.05,45.714937,0,1641,0.000501,0.000277,-0.033161,0.014949,0.000006,7.923194,C,42.071409,0.014185
565,SPXW 12/31/24 C7500,7500,0,0.1,0,50.963975,0,0,0.000869,0.000414,-0.063546,0.024852,0.000011,7.923194,C,44.031897,0.011824
566,SPXW 12/31/24 C7600,7600,0,0.05,0.05,50.948928,0,6,0.000454,0.000227,-0.033496,0.013642,0.000006,7.923194,C,45.91488,0.009845
567,SPXW 12/31/24 C7800,7800,0,0.1,0.2,58.946606,0,6,0.00076,0.000316,-0.064357,0.021967,0.00001,7.923194,C,49.465456,0.006785
568,SPXW 12/31/24 C8000,8000,0,0.1,0,64.045943,0,0,0.000704,0.000271,-0.064823,0.020475,0.000009,7.923194,C,52.742193,0.00465

In [ ]:
S0 = 5975
r =

In [11]:
dir_path.

In [63]:
atm = pd.read_excel("../data/sample/Bloomberg/SPX_12232024/ATMs.xlsx", engine="openpyxl", header=None).dropna()
atm.columns = atm.iloc[0, :]
atm = atm.drop(atm.index[0])
call_atm = atm.iloc[:, :15]
put_atm = atm.iloc[:, 15:]
cols = [
    'strike',
    'ticker',
    'bid',
    'ask',
    'last_p',
    'iv',
    'vol',
    'div',
    'ndvs',
    'tau',
    'csize',
    'r',
    'hv30',
    'hv60',
    'hv90'
]
call_atm.columns = cols
call_atm.loc[:, ['refdate']] = datetime(2024, 12, 23)
call_atm.loc[:, ['cp_flag']] = 'C'
put_atm.columns = cols
put_atm.loc[:, ['refdate']] = datetime(2024, 12, 23)
put_atm.loc[:, ['cp_flag']] = 'P'

atm_all = pd.concat([call_atm, put_atm], ignore_index=True, axis=0)
print(atm_all.shape)

(66, 17)

In [75]:
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS atms;"))

with engine.connect() as conn:
    conn.execute(text("""
        CREATE TABLE atms (
            strike     NUMERIC,
            ticker     TEXT NOT NULL,
            bid        NUMERIC,
            ask        NUMERIC,
            last_p     NUMERIC,
            iv         NUMERIC,
            vol        NUMERIC,
            div        NUMERIC,
            ndvs       NUMERIC,
            tau        NUMERIC,
            csize      NUMERIC,
            r          NUMERIC,
            hv30       NUMERIC,
            hv60       NUMERIC,
            hv90       NUMERIC,
            refdate    DATE NOT NULL,
            cp_flag    CHAR(1),
            PRIMARY KEY (refdate, ticker)
        )
    """))

with engine.connect() as conn:
    result = conn.execute(text("""
        SELECT
            tc.constraint_name,
            tc.table_name,
            kcu.column_name
        FROM 
            information_schema.table_constraints AS tc
        JOIN 
            information_schema.key_column_usage AS kcu
            ON tc.constraint_name = kcu.constraint_name
        WHERE 
            tc.table_name = 'atms'
            AND tc.constraint_type = 'PRIMARY KEY';
    """))
    pk_info = result.fetchall()
    print("Primary Key columns in 'atm':", [row[2] for row in pk_info])
    
atm_all.to_sql("atm", con=engine, if_exists='append', index=False, method='multi')
print("successfully inserted atm table")
df = pd.read_sql("SELECT * FROM atm", con=engine)
display(df)

Primary Key columns in 'atm': []
successfully inserted atm table

,strike,ticker,bid,ask,last_p,iv,vol,div,ndvs,tau,csize,r,hv30,hv60,hv90,refdate,cp_flag
0,5975,SPXW 12/31/24 C5975,44.7999992370605,45.5999984741211,45.5,13.1352886935549,414,1.202712,1.574813,7.913229,100,4.597907,12.45479,12.67761,12.7425,2024-12-23,C
1,5975,SPX 1/17/25 C5975,90.1999969482422,91.9000015258789,90.120002746582,13.2713584036626,451,1.261231,5.160742,24.652812,100,4.597907,12.45479,12.67761,12.7425,2024-12-23,C
2,5975,SPXW 1/17/25 C5975,91.5999984741211,92.6999969482422,91.9000015258789,13.3309698785267,58,1.261231,5.160742,24.913229,100,4.597907,12.45479,12.67761,12.7425,2024-12-23,C
3,5975,SPXW 1/31/25 C5975,119.199996948242,120.300003051758,119.830001831055,13.7285947171,15,1.025257,6.544474,38.913229,100,4.597907,12.45479,12.67761,12.7425,2024-12-23,C
4,5975,SPX 2/21/25 C5975,151.699996948242,153.399993896484,146.610000610352,13.845976050819,23,1.278409,12.554470,59.652813,100,4.597907,12.45479,12.67761,12.7425,2024-12-23,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,5975,SPX 6/18/26 P5975,330.5,339.700012207031,316.489990234375,16.895224106717,0,1.312448,116.428398,541.611146,100,4.402399,12.45479,12.67761,12.7425,2024-12-23,P
260,5950,SPX 12/18/26 P5950,0,0,353.200012207031,17.5613783221793,0,1.311219,155.593201,724.652812,100,4.395222,12.45479,12.67761,12.7425,2024-12-23,P
261,6000,SPX 12/17/27 P6000,400,0,444.519989013672,18.0333941661039,15,1.321531,235.549698,1088.652812,100,4.367864,12.45479,12.67761,12.7425,2024-12-23,P
262,6000,SPX 12/15/28 P6000,0,0,500,18.7587826234451,0,1.316586,313.106598,1452.652812,100,4.350152,12.45479,12.67761,12.7425,2024-12-23,P
263,6000,SPX 12/21/29 P6000,0,0,509.399993896484,19.0901456502538,0,1.317141,393.218689,1823.652812,100,4.337728,12.45479,12.67761,12.7425,2024-12-23,P

In [62]:
df[df.duplicated()]

,strike,ticker,bid,ask,last,iv,vol,div,ndvs,tau,size,r,hv30,hv60,hv90,refdate,cp_flag
66,5975,SPXW 12/31/24 C5975,44.7999992370605,45.5999984741211,45.5,13.1352886935549,414,1.202712,1.574813,7.913229,100,4.597907,12.45479,12.67761,12.7425,2024-12-23,C
67,5975,SPX 1/17/25 C5975,90.1999969482422,91.9000015258789,90.120002746582,13.2713584036626,451,1.261231,5.160742,24.652812,100,4.597907,12.45479,12.67761,12.7425,2024-12-23,C
68,5975,SPXW 1/17/25 C5975,91.5999984741211,92.6999969482422,91.9000015258789,13.3309698785267,58,1.261231,5.160742,24.913229,100,4.597907,12.45479,12.67761,12.7425,2024-12-23,C
69,5975,SPXW 1/31/25 C5975,119.199996948242,120.300003051758,119.830001831055,13.7285947171,15,1.025257,6.544474,38.913229,100,4.597907,12.45479,12.67761,12.7425,2024-12-23,C
70,5975,SPX 2/21/25 C5975,151.699996948242,153.399993896484,146.610000610352,13.845976050819,23,1.278409,12.554470,59.652813,100,4.597907,12.45479,12.67761,12.7425,2024-12-23,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,5975,SPX 6/18/26 P5975,330.5,339.700012207031,316.489990234375,16.895224106717,0,1.312448,116.428398,541.611146,100,4.402399,12.45479,12.67761,12.7425,2024-12-23,P
194,5950,SPX 12/18/26 P5950,0,0,353.200012207031,17.5613783221793,0,1.311219,155.593201,724.652812,100,4.395222,12.45479,12.67761,12.7425,2024-12-23,P
195,6000,SPX 12/17/27 P6000,400,0,444.519989013672,18.0333941661039,15,1.321531,235.549698,1088.652812,100,4.367864,12.45479,12.67761,12.7425,2024-12-23,P
196,6000,SPX 12/15/28 P6000,0,0,500,18.7587826234451,0,1.316586,313.106598,1452.652812,100,4.350152,12.45479,12.67761,12.7425,2024-12-23,P
197,6000,SPX 12/21/29 P6000,0,0,509.399993896484,19.0901456502538,0,1.317141,393.218689,1823.652812,100,4.337728,12.45479,12.67761,12.7425,2024-12-23,P

In [76]:
import pandas as pd
import re
from pathlib import Path

# 옵션 컬럼 정의
cols = [
    'ticker',  # Option ticker (e.g., "SPXW 12/31/24 C1200")
    'strike',  # Strike price of the option
    'bid',     # Best bid price (buying offer)
    'ask',     # Best ask price (selling offer)
    'last',    # Last traded price
    'iv',      # Implied volatility (IV)
    'volume',  # Trading volume
    'open',    # Open interest
    'delta',   # Delta
    'gamma',   # Gamma
    'theta',   # Theta
    'vega',    # Vega
    'rho',     # Rho
    'tau',     # Time to expiration
    'option_type',    # Option type: "Euro" or "American"
    'thiv',    # Theoretical IV
    'thpr'     # Theoretical price
]

underlying_tickers = ['SPX', 'SPXW']
ticker_pattern = r'^(' + '|'.join(underlying_tickers) + r')\d{1,2}/\d{1,2}/\d{2,4}[CP]\d+(\.\d+)?$'

for f in files:
    
    df = pd.read_excel(f, engine="openpyxl", header=None)
    half = df.shape[1] // 2
    
    df_call = df.iloc[:, :half].copy()
    df_call.columns = cols
    df_call["type"] = "C"
    mask_call = (
        df_call["ticker"]
        .astype(str)
        .apply(lambda x: re.sub(r"\s+", "", x))
        .str.match(ticker_pattern)
    )
    # a = df_call["ticker"].astype(str).apply(lambda x: re.sub(r"\s+", "", x))
    # b = df_call["ticker"].astype(str).apply(lambda x: re.sub(r"\s+", "", x)).str.match(ticker_pattern)
    # display(pd.concat([a, mask_call], axis=1))
    invalid_call = df_call[~mask_call]
    valid_call = df_call[mask_call]

    df_put = df.iloc[:, half:].copy()
    df_put.columns = cols
    df_put["type"] = "P"
    mask_put = (
        df_put["ticker"]
        .astype(str)
        .apply(lambda x: re.sub(r"\s+", "", x))
        .str.match(ticker_pattern)
    )
    invalid_put = df_put[~mask_put]
    valid_put = df_put[mask_put]

In [77]:
valid_call

,ticker,strike,bid,ask,last,iv,volume,open,delta,gamma,theta,vega,rho,tau,cp_flag,thiv,thpr,type
3,SPX 12/21/29 C400,400,0.1,0,5485,0,0,14,1,0,0,0,0,1823.662778,Euro,40.449263,5579.212973,C
4,SPX 12/21/29 C800,800,0,0,0,0,0,0,0,0,0,0,0,1823.662778,Euro,37.628031,5255.0825,C
5,SPX 12/21/29 C1200,1200,0,0,0,0,0,0,0,0,0,0,0,1823.662778,Euro,35.277992,4934.138518,C
6,SPX 12/21/29 C1600,1600,0,0,0,0,0,0,0,0,0,0,0,1823.662778,Euro,33.080748,4616.402073,C
7,SPX 12/21/29 C1800,1800,0,0,3102.399902,0,0,0,0,0,0,0,0,1823.662778,Euro,32.030175,4458.653046,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,SPXW 12/31/24 C7400,7400,0,0.05,0.05,45.714937,0,1641,0.000501,0.000277,-0.033161,0.014949,0.000006,7.923194,Euro,42.071409,0.014185,C
565,SPXW 12/31/24 C7500,7500,0,0.1,0,50.963975,0,0,0.000869,0.000414,-0.063546,0.024852,0.000011,7.923194,Euro,44.031897,0.011824,C
566,SPXW 12/31/24 C7600,7600,0,0.05,0.05,50.948928,0,6,0.000454,0.000227,-0.033496,0.013642,0.000006,7.923194,Euro,45.91488,0.009845,C
567,SPXW 12/31/24 C7800,7800,0,0.1,0.2,58.946606,0,6,0.00076,0.000316,-0.064357,0.021967,0.00001,7.923194,Euro,49.465456,0.006785,C
568,SPXW 12/31/24 C8000,8000,0,0.1,0,64.045943,0,0,0.000704,0.000271,-0.064823,0.020475,0.000009,7.923194,Euro,52.742193,0.00465,C

In [13]:
pd.read_excel('../data/sample/raw_data/SPX_12232024/20251017.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: '../data/sample/raw_data/SPX_12232024/20251017.xlsx'

In [16]:
from pathlib import Path

print("현재 작업 디렉토리:", Path.cwd())

현재 작업 디렉토리: /Users/young/Library/CloudStorage/GoogleDrive-wjddudwls528@gmail.com/My Drive/1. Project/RossRecoveryTheorem/notebooks

In [41]:
import pandas as pd
pd.read_excel("../data/sample/raw_data/SPX_12232024/" + "20250117.xlsx", engine='openpyxl')

,Calls,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,Ticker,Strike,Bid,Ask,Last,IVM,Volm,OInt,DM,GM,...,OInt,DM,GM,TM,VM,RM,DyEx,XTyp,tIVM,tPxM
1,17-Jan-25 (25d); CSize 100; R 4.60; FF 0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SPX 1/17/25 C200,200,5755.299805,5788,5752.200195,0,2,67,1,0,...,272,-0.000031,0.000001,-0.015404,0.001992,-0.000002,24.667847,Euro,198.672734,0
3,SPX 1/17/25 C400,400,5556.100098,5588.799805,5501.490234,0,0,20,1,0,...,1298,-0.00004,0.000002,-0.015754,0.002586,-0.000002,24.667847,Euro,176.490562,0
4,SPX 1/17/25 C600,600,5356.899902,5389.600098,5448.049805,0,0,47,1,0,...,762,-0.000048,0.000003,-0.015887,0.003079,-0.000002,24.667847,Euro,162.113841,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,SPX 1/17/25 C8200,8200,0,0.15,0.1,38.542684,0,98,0.00094,0.000321,...,0,-1,0,0,0,0,24.667847,Euro,38.208624,2199.51511
431,SPX 1/17/25 C8400,8400,0,0.05,0.05,38.006882,790,709,0.000339,0.000127,...,0,-1,0,0,0,0,24.667847,Euro,40.388485,2398.900561
432,SPX 1/17/25 C8600,8600,0,0.15,0.1,43.835478,0,1516,0.000837,0.000253,...,2,-1,0,0,0,0,24.667847,Euro,42.453601,2598.288767
433,SPX 1/17/25 C8800,8800,0,0.05,0.05,42.807212,0,800,0.000305,0.000102,...,0,-1,0,0,0,0,24.667847,Euro,44.413195,2797.679336
434,SPX 1/17/25 C9000,9000,0,0.05,0.05,45.108727,0,15778,0.000291,0.000092,...,981,-1,0,0,0,0,24.667847,Euro,46.275434,2997.071928

In [12]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5